# Tell Render how to build & run your service
services:
  - type: web
    name: card-edge-detector
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn main:app --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: "10000"
